# Linear Algebra for Data Science - Part 2
## Matrix Multiplication, Transpose, Inverse, Determinants

We continue using the same House Price dataset.

In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)

data = {
    'Area': [1000, 1500, 2000, 2500, 3000],
    'Bedrooms': [2, 3, 3, 4, 4],
    'Age': [10, 5, 20, 15, 8],
    'Distance': [5, 3, 10, 2, 7],
    'Price': [200000, 300000, 250000, 400000, 500000]
}

df = pd.DataFrame(data)

X = df[['Area','Bedrooms','Age','Distance']].to_numpy()
y = df['Price'].to_numpy()

X, y

(array([[1000,    2,   10,    5],
        [1500,    3,    5,    3],
        [2000,    3,   20,   10],
        [2500,    4,   15,    2],
        [3000,    4,    8,    7]]),
 array([200000, 300000, 250000, 400000, 500000]))

# 1. Matrix Multiplication

Used to compute predictions in Machine Learning models.

In [2]:
w = np.array([120, 50000, -3000, -8000])

pred = X @ w
pred

array([150000, 291000, 250000, 439000, 480000])

# 2. Transpose

Flips rows and columns. Used in ML formulas.

In [3]:
X.T

array([[1000, 1500, 2000, 2500, 3000],
       [   2,    3,    3,    4,    4],
       [  10,    5,   20,   15,    8],
       [   5,    3,   10,    2,    7]])

# 3. Matrix Inverse

Used to solve linear equations (Linear Regression).

In [4]:
A = np.array([
    [2,1],
    [1,3]
])

np.linalg.inv(A)

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

Important: In real ML, inverse is rarely used directly due to instability.

# 4. Determinants

Tells whether a matrix is invertible or not.

In [5]:
np.linalg.det(A)

np.float64(5.000000000000001)

# 5. Full Linear Regression Using Linear Algebra

This is the real ML connection.

In [6]:
w_best = np.linalg.inv(X.T @ X) @ X.T @ y
w_best

array([   75.69170765, 76926.11471192, -6857.83962479,  1965.1988405 ])

In [7]:
pred_final = X @ w_best
pred_final

array([170791.53502915, 315922.30400938, 264656.95534638, 397996.53128359,
       493673.25668501])

# 6. Compare Predictions

In [8]:
pd.DataFrame({
    "Actual": y,
    "Predicted": pred_final
})

,Actual,Predicted
0,200000,170791.535029
1,300000,315922.304009
2,250000,264656.955346
3,400000,397996.531284
4,500000,493673.256685


# Key Takeaways

- Matrix multiplication = ML prediction engine
- Transpose = required for formulas
- Inverse = solving equations (rare in practice)
- Determinant = checks matrix stability
- Linear regression = pure linear algebra