# Linear Algebra for Data Science - Part 6
## Eigenvalues, Eigenvectors, SVD, PCA

This is the core of modern Machine Learning and Data Science.

In [2]:
import numpy as np
import pandas as pd

np.set_printoptions(suppress=True)

data = {
    'Area': [1000, 1500, 2000, 2500, 3000],
    'Bedrooms': [2, 3, 3, 4, 4],
    'Age': [10, 5, 20, 15, 8],
    'Distance': [5, 3, 10, 2, 7],
    'Price': [200000, 300000, 250000, 400000, 500000]
}

df = pd.DataFrame(data)
X = df[['Area','Bedrooms','Age','Distance']].to_numpy()
X

array([[1000,    2,   10,    5],
       [1500,    3,    5,    3],
       [2000,    3,   20,   10],
       [2500,    4,   15,    2],
       [3000,    4,    8,    7]])

# 1. Eigenvalues & Eigenvectors

Eigenvectors are directions that do not change when a matrix is applied.

Eigenvalue = how much the vector is stretched.

In [3]:
A = np.array([[2, 1],
              [1, 2]])

eigvals, eigvecs = np.linalg.eig(A)
eigvals, eigvecs

(array([3., 1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

# Why it matters in Data Science

- PCA uses eigenvectors
- PageRank uses eigenvalues
- Clustering uses spectral methods
- Data variance directions come from eigenvectors

# 2. Covariance Matrix (Preparation for PCA)

Shows how features move together.

In [4]:
X_centered = X - X.mean(axis=0)
cov_matrix = np.cov(X_centered.T)

cov_matrix

array([[625000.  ,    625.  ,    750.  ,    375.  ],
       [   625.  ,      0.7 ,      0.35,     -0.35],
       [   750.  ,      0.35,     35.3 ,      9.45],
       [   375.  ,     -0.35,      9.45,     10.3 ]])

# 3. PCA (Principal Component Analysis)

PCA finds the most important directions (variance directions).

In [5]:
eigvals, eigvecs = np.linalg.eig(cov_matrix)

eigvals

array([625001.75006437,     37.37762756,      0.0203686 ,      7.15193947])

Sort eigenvectors by largest eigenvalues → principal components.

In [6]:
idx = np.argsort(eigvals)[::-1]
components = eigvecs[:, idx]

components

array([[ 0.9999986 , -0.00131122, -0.00011209,  0.0010336 ],
       [ 0.001     , -0.01627406, -0.07920482, -0.99672501],
       [ 0.00120007,  0.9494759 , -0.31369605,  0.00942648],
       [ 0.00060002,  0.31341498,  0.94621423, -0.08030767]])

# 4. Dimensionality Reduction

Project data onto fewer dimensions.

In [7]:
X_pca = X_centered @ components[:, :2]
X_pca

array([[-1000.00196002,    -0.31377414],
       [ -500.00886049,    -6.35986987],
       [    0.01264072,     9.42056128],
       [  500.00214011,     1.49397568],
       [  999.99603968,    -4.24089295]])

# 5. Singular Value Decomposition (SVD)

SVD = more stable version of PCA.

In [8]:
U, S, Vt = np.linalg.svd(X_centered)

S

array([1581.14104376,   12.22744905,    5.34862206,    0.28543718])

# Why SVD matters

- Image compression
- Recommendation systems
- NLP embeddings (LSA)
- Noise reduction
- PCA implementation

# 6. Relationship: Eigen vs SVD

- Eigen → square matrices
- SVD → any matrix
- PCA uses both depending on implementation

# 7. Real Data Science Meaning

- Eigenvectors = important directions in data
- Eigenvalues = importance score
- PCA = remove noise, keep signal
- SVD = compress + simplify data

# Key Takeaways

- Eigenvectors = directions of maximum variance
- Eigenvalues = strength of those directions
- PCA = dimensionality reduction
- SVD = robust decomposition method
- These power modern ML systems